import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/Components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    safelist: ["border-red-400"],
    theme: {
        extend: {
            keyframes: {
                fadein: {
                    "0%": { opacity: "0" },
                    "100%": { opacity: "1" },
                },
                slider: {
                    "0%": {
                        transform: "translateX(0px)",
                    },
                    "100%": {
                        transform: "translateX(-1400px)",
                    },
                },
            },
            animation: {
                fadein: "fadein 3s ease-in-out",
                slider: "slider 30s linear infinite",
            },
            fontFamily: {
                spoqaBold: ["SpoqaHanSansNeo-Bold", "sans-serif"],
                spoqaMedium: ["SpoqaHanSansNeo-Medium", "sans-serif"],
                spoqaRegular: ["SpoqaHanSansNeo-Regular", "sans-serif"],
                spoqaLight: ["SpoqaHanSanNeo-Light", "sans-serif"],
            },
            fontSize: {
                H1_B: ["80px", { lineHeight: "100px", fontWeight: "700", letterSpacing: "0px" }],
                H2_B: ["60px", { lineHeight: "80px", fontWeight: "700", letterSpacing: "0px" }],
                H3_B: ["50px", { lineHeight: "72px", fontWeight: "700", letterSpacing: "0px" }],
                H4_B: ["40px", { lineHeight: "62px", fontWeight: "700", letterSpacing: "0px" }],
                H5_B: ["30px", { lineHeight: "46px", fontWeight: "700", letterSpacing: "0px" }],
                H6_B: ["26px", { lineHeight: "40px", fontWeight: "700", letterSpacing: "0px" }],
                H7_B: ["22px", { lineHeight: "36px", fontWeight: "700", letterSpacing: "0px" }],
                H1_L: ["80px", { lineHeight: "100px", fontWeight: "300", letterSpacing: "0px" }],
                H2_L: ["60px", { lineHeight: "80px", fontWeight: "300", letterSpacing: "0px" }],
                H3_L: ["50px", { lineHeight: "72px", fontWeight: "300", letterSpacing: "0px" }],
                H4_L: ["40px", { lineHeight: "62px", fontWeight: "300", letterSpacing: "0px" }],
                H5_L: ["30px", { lineHeight: "46px", fontWeight: "300", letterSpacing: "0px" }],
                H6_L: ["26px", { lineHeight: "40px", fontWeight: "300", letterSpacing: "0px" }],
                H7_L: ["22px", { lineHeight: "36px", fontWeight: "300", letterSpacing: "0px" }],
                SH1_M: ["40px", { lineHeight: "56px", fontWeight: "500", letterSpacing: "0px" }],
                SH2_M: ["30px", { lineHeight: "42px", fontWeight: "500", letterSpacing: "0px" }],
                SH3_M: ["24px", { lineHeight: "34px", fontWeight: "500", letterSpacing: "0px" }],
                SH4_M: ["20px", { lineHeight: "28px", fontWeight: "500", letterSpacing: "0px" }],
                SH5_M: ["16px", { lineHeight: "24px", fontWeight: "500", letterSpacing: "0px" }],
                P1_M: ["36px", { lineHeight: "64px", fontWeight: "500", letterSpacing: "0px" }],
                P1_R: ["36px", { lineHeight: "64px", fontWeight: "400", letterSpacing: "0px" }],
                P2_M: ["32px", { lineHeight: "60px", fontWeight: "500", letterSpacing: "0px" }],
                P2_R: ["32px", { lineHeight: "60px", fontWeight: "400", letterSpacing: "0px" }],
                P3_M: ["28px", { lineHeight: "54px", fontWeight: "500", letterSpacing: "0px" }],
                P3_R: ["28px", { lineHeight: "54px", fontWeight: "400", letterSpacing: "0px" }],
                P4_M: ["24px", { lineHeight: "48px", fontWeight: "500", letterSpacing: "0px" }],
                P4_R: ["24px", { lineHeight: "48px", fontWeight: "400", letterSpacing: "0px" }],
                P5_M: ["20px", { lineHeight: "38px", fontWeight: "500", letterSpacing: "0px" }],
                P5_R: ["20px", { lineHeight: "38px", fontWeight: "400", letterSpacing: "0px" }],
                P6_M: ["16px", { lineHeight: "32px", fontWeight: "500", letterSpacing: "0px" }],
                P6_R: ["16px", { lineHeight: "32px", fontWeight: "400", letterSpacing: "0px" }],
                P7_M: ["14px", { lineHeight: "22px", fontWeight: "500", letterSpacing: "0px" }],
                P7_R: ["14px", { lineHeight: "22px", fontWeight: "400", letterSpacing: "0px" }],
                P8_M: ["12px", { lineHeight: "140%", fontWeight: "500", letterSpacing: "-0.4px" }],
                P8_R: ["12px", { lineHeight: "140%", fontWeight: "400", letterSpacing: "-0.4px" }],
                P9_M: ["10px", { lineHeight: "140%", fontWeight: "500", letterSpacing: "-0.4px" }],
                P9_R: ["10px", { lineHeight: "140%", fontWeight: "400", letterSpacing: "-0.4px" }],
                P10_M: ["8px", { lineHeight: "14px", fontWeight: "500", letterSpacing: "-0.4px" }],
                P10_R: ["8px", { lineHeight: "14px", fontWeight: "400", letterSpacing: "-0.4px" }],
            },
            colors: {
                primary_1: "#0099ff",
                primary_2: "#33ADFF",
                primary_3: "#66C2FF",
                primary_4: "#99D6FF",
                primary_5: "#CCEBFF",
                secondary_1: "#00D0ED",
                secondary_2: "#33DAF0",
                secondary_3: "#66E3F4",
                secondary_4: "#99ECF8",
                secondary_5: "#CCF6FB",
                success: "#07CF57",
                info: "#0B79E7",
                alert: "#F13131",
                warning: "#FF8039",
                favorite: "#FFD645",
                disabled: "#D9D9D9",
                gray_1: "#FAFAFA",
                gray_2: "#F1F1F1",
                gray_3: "#DBDBDB",
                gray_4: "#9A9A9A",
                gray_5: "#565656",
                black: "#101010",
                blue: "#F1F9FF",
                sky_blue: "#E1FFFF",
                green: "#E0FFEC",
                red: "#FFF1F1",
            },
            screens: {
                sm: { max: "790px" },
                lg: { min: "791px", max: "1500px" },
            },
        },
    },
    plugins: [],
};

export default config;
