const SKILL_TAG = [
    "HTML5",
    "CSS3",
    "JavaScript",
    "TypeScript",
    "React",
    "Vue.js",
    "Angular JS",
    "Next.js",
    "Svelte",
    "React Native",
    "Flutter",
    "IOS",
    "Android Studio",
    "Kotlin",
    "C#",
    "Unity",
    "Unreal",
    "PHP",
    "Node.js",
    "JAVA",
    "Spring",
    "SpringBoot",
    "Nest.js",
    "Express.js",
    "Python",
    "Django",
    "Flask",
    "MySQL",
];
